In [1]:
import tensorflow as tf

In [2]:
import numpy as np
tf.set_random_seed(777)

In [6]:
xy = np.loadtxt('data-01-test-score.csv',delimiter=',', dtype=np.float32)
x_data =xy[:,0:-1]
y_data = xy[:, [-1]]

In [7]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [8]:
X= tf.placeholder(tf.float32,shape=[None, 3])

In [9]:
Y= tf.placeholder(tf.float32, shape=[None, 1])

In [10]:
W= tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

Instructions for updating:
Colocations handled automatically by placer.


In [11]:
hypothesis = tf.matmul(X,W) +b

In [12]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [14]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [15]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [16]:
for step in range(2001):
    cost_val, hy_val,_= sess.run([cost, hypothesis,train],
                                feed_dict={X:x_data, Y:y_data})
    if step %10==0:
        print(step, "Cost: ",cost_val, "\nPrediction:\n", hy_val)

0 Cost:  20344.273 
Prediction:
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]]
10 Cost:  7.591933 
Prediction:
 [[154.9885 ]
 [181.46912]
 [181.56465]
 [193.78198]
 [140.56638]
 [ 97.16199]]
20 Cost:  6.624332 
Prediction:
 [[155.87779]
 [182.55698]
 [182.62657]
 [194.94084]
 [141.39882]
 [ 97.78158]]
30 Cost:  6.5896964 
Prediction:
 [[155.8728 ]
 [182.56958]
 [182.62921]
 [194.9461 ]
 [141.41107]
 [ 97.79651]]
40 Cost:  6.5553193 
Prediction:
 [[155.86182]
 [182.5749 ]
 [182.62471]
 [194.9436 ]
 [141.41779]
 [ 97.80733]]
50 Cost:  6.521196 
Prediction:
 [[155.85083]
 [182.58017]
 [182.62018]
 [194.94107]
 [141.42441]
 [ 97.81806]]
60 Cost:  6.487265 
Prediction:
 [[155.83986]
 [182.5854 ]
 [182.61565]
 [194.9385 ]
 [141.43102]
 [ 97.82877]]
70 Cost:  6.4535728 
Prediction:
 [[155.82895]
 [182.59062]
 [182.61115]
 [194.93599]
 [141.4376 ]
 [ 97.83946]]
80 Cost:  6.4200826 
Prediction:
 [[155.81807 ]
 [182.59584 ]
 [182.60664 ]
 [194.93347 ]
 [141

1050 Cost:  4.021121 
Prediction:
 [[154.91602 ]
 [183.02527 ]
 [182.23297 ]
 [194.72972 ]
 [141.98051 ]
 [ 98.736404]]
1060 Cost:  4.003453 
Prediction:
 [[154.90816 ]
 [183.02899 ]
 [182.2297  ]
 [194.728   ]
 [141.98514 ]
 [ 98.744194]]
1070 Cost:  3.9858675 
Prediction:
 [[154.9003 ]
 [183.0327 ]
 [182.22644]
 [194.72629]
 [141.98973]
 [ 98.75195]]
1080 Cost:  3.968385 
Prediction:
 [[154.89249]
 [183.03642]
 [182.22318]
 [194.72458]
 [141.9943 ]
 [ 98.7597 ]]
1090 Cost:  3.9510365 
Prediction:
 [[154.8847 ]
 [183.04013]
 [182.21996]
 [194.7229 ]
 [141.99886]
 [ 98.76742]]
1100 Cost:  3.933756 
Prediction:
 [[154.8769  ]
 [183.04381 ]
 [182.2167  ]
 [194.72119 ]
 [142.00339 ]
 [ 98.775116]]
1110 Cost:  3.916642 
Prediction:
 [[154.86916]
 [183.04747]
 [182.21349]
 [194.71948]
 [142.00792]
 [ 98.78277]]
1120 Cost:  3.8996294 
Prediction:
 [[154.86145]
 [183.05112]
 [182.21027]
 [194.7178 ]
 [142.01242]
 [ 98.79041]]
1130 Cost:  3.8826973 
Prediction:
 [[154.85376 ]
 [183.05478 ]
 [1

In [17]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100,70,101]]}))

Your score will be  [[171.15341]]


In [18]:
print("Other score will be", sess.run(hypothesis, feed_dict={X:[[60,70,110],[90,100,80]]}))

Other score will be [[106.725494]
 [197.8313  ]]
