In [1]:
import tensorflow as tf

In [2]:
x_data=[[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data =[[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [3]:
x_test =[[2,1,1],[3,1,2],[3,3,4]]
y_test =[[0,0,1],[0,0,1],[0,0,1]]

In [4]:
X = tf.placeholder("float", [None,3])
Y = tf.placeholder("float", [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b= tf.Variable(tf.random_normal([3]))

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y* tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

Instructions for updating:
Use tf.cast instead.


In [7]:
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

Instructions for updating:
Use `tf.math.argmax` instead


In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _= sess.run([cost, W, optimizer], feed_dict={X:x_data,Y:y_data})
        print(step, cost_val, W_val)
        
    print("Prediction: ", sess.run(prediction, feed_dict={X:x_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X:x_test, Y: y_test}))

0 7.3160634 [[-0.15604815 -0.59117246 -2.8281705 ]
 [ 0.13243562  0.87827325 -0.333313  ]
 [ 0.70163894 -1.8855733   1.1303986 ]]
1 4.9005065 [[-0.22265413 -0.5567181  -2.7960188 ]
 [-0.1165708   1.0466654  -0.25269875]
 [ 0.45520434 -1.7016381   1.192898  ]]
2 3.473046 [[-0.2387689  -0.529355   -2.8072672 ]
 [-0.12182756  1.1958745  -0.39665097]
 [ 0.45605838 -1.5295091   1.019915  ]]
3 2.7138243 [[-0.2747324  -0.5107942  -2.7898645 ]
 [-0.238607    1.3052242  -0.38922122]
 [ 0.33178934 -1.3858535   1.0005286 ]]
4 2.3589902 [[-0.27903405 -0.50980055 -2.7865565 ]
 [-0.1949579   1.3236433  -0.45128942]
 [ 0.3607274  -1.3146569   0.90039384]]
5 2.2545881 [[-0.29545003 -0.5140659  -2.765875  ]
 [-0.21000613  1.3115597  -0.42415756]
 [ 0.32147846 -1.2730167   0.8980027 ]]
6 2.2149005 [[-0.30394664 -0.5219274  -2.749517  ]
 [-0.18581347  1.2803975  -0.41718808]
 [ 0.3243967  -1.2496684   0.8717361 ]]
7 2.1815362 [[-0.31572214 -0.5282195  -2.7314494 ]
 [-0.177899    1.2572707  -0.40197563]
 