In [1]:
import tensorflow as tf

In [2]:
x1_data =[73., 93., 89., 96., 73.] 
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [7]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name ='weight2')
w3 = tf.Variable(tf.random_normal([1]), name ='weight3')
b= tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1*w1 + x2*w2 + x3*w3 +b

In [8]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

Instructions for updating:
Use tf.cast instead.


In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step %10==0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  179642.66 
Prediction: 
 [-218.65851 -271.79437 -263.3243  -283.68875 -212.29741]
10 Cost:  36.553627 
Prediction: 
 [156.22232 178.8238  180.65709 199.79704 131.41957]
20 Cost:  34.745594 
Prediction: 
 [157.33588 180.20152 181.99422 201.25438 132.4792 ]
30 Cost:  34.582703 
Prediction: 
 [157.3186  180.21996 181.99207 201.25327 132.502  ]
40 Cost:  34.420708 
Prediction: 
 [157.29796 180.23422 181.9859  201.24774 132.5216 ]
50 Cost:  34.259495 
Prediction: 
 [157.27737 180.24846 181.97972 201.24222 132.54117]
60 Cost:  34.09911 
Prediction: 
 [157.25684 180.26265 181.97356 201.23671 132.56068]
70 Cost:  33.939697 
Prediction: 
 [157.23634 180.27678 181.9674  201.23122 132.58012]
80 Cost:  33.781 
Prediction: 
 [157.21594 180.29092 181.9613  201.22574 132.59955]
90 Cost:  33.623367 
Prediction: 
 [157.19556 180.30496 181.95517 201.22028 132.61887]
100 Cost:  33.466408 
Prediction: 
 [157.17526 180.31902 181.94911 201.21483 132.63818]
110 Cost:  33.31034 
Prediction: 
 [157.15

1280 Cost:  19.758986 
Prediction: 
 [155.13423 181.73056 181.33946 200.6515  134.59381]
1290 Cost:  19.675694 
Prediction: 
 [155.11963 181.74068 181.33511 200.64735 134.60793]
1300 Cost:  19.592815 
Prediction: 
 [155.10509 181.75075 181.3308  200.6432  134.62202]
1310 Cost:  19.510372 
Prediction: 
 [155.09056 181.76079 181.32646 200.63907 134.63608]
1320 Cost:  19.428375 
Prediction: 
 [155.0761  181.77083 181.32216 200.63493 134.65009]
1330 Cost:  19.346842 
Prediction: 
 [155.06166 181.7808  181.31789 200.63081 134.66406]
1340 Cost:  19.265606 
Prediction: 
 [155.04726 181.79079 181.31358 200.62668 134.67801]
1350 Cost:  19.184942 
Prediction: 
 [155.03293 181.80074 181.30933 200.6226  134.69193]
1360 Cost:  19.104635 
Prediction: 
 [155.01862 181.81065 181.30508 200.6185  134.7058 ]
1370 Cost:  19.024769 
Prediction: 
 [155.00436 181.82054 181.30084 200.61441 134.71964]
1380 Cost:  18.945356 
Prediction: 
 [154.99013 181.83041 181.29663 200.61035 134.73343]
1390 Cost:  18.866322