In [1]:
import tensorflow as tf

In [2]:
x_data =[[73, 80, 75], [93, 88, 93], [89,91, 90], [96,98,100], [73, 66, 70]]
y_data=[[152],[185], [180], [196], [142]]

In [3]:
X= tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [7]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
hypothesis = tf.matmul(X,W)+b

In [10]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [11]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train =optimizer.minimize(cost)

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [17]:
for step in range(2001):
    cost_val, hy_val, _= sess.run([cost,hypothesis, train],
                                 feed_dict={X:x_data, Y:y_data})
    if step%10==0:
        print(step, "Cost: ", cost_val, "\Prediction:\n", hy_val)

0 Cost:  556.09894 \Prediction:
 [[174.99445]
 [208.07748]
 [206.30655]
 [222.43338]
 [160.1224 ]]
10 Cost:  2.459228 \Prediction:
 [[154.17444]
 [183.06372]
 [181.65465]
 [195.58904]
 [141.045  ]]
20 Cost:  2.443784 \Prediction:
 [[154.10597]
 [182.99173]
 [181.57835]
 [195.50687]
 [140.9919 ]]
30 Cost:  2.4334748 \Prediction:
 [[154.10033]
 [182.99521]
 [181.57643]
 [195.50569]
 [140.99634]]
40 Cost:  2.4231691 \Prediction:
 [[154.09486]
 [182.99892]
 [181.57469]
 [195.50476]
 [141.00093]]
50 Cost:  2.412982 \Prediction:
 [[154.08945]
 [183.0026 ]
 [181.573  ]
 [195.50383]
 [141.00552]]
60 Cost:  2.4027913 \Prediction:
 [[154.08401]
 [183.0063 ]
 [181.5713 ]
 [195.5029 ]
 [141.0101 ]]
70 Cost:  2.3926888 \Prediction:
 [[154.07861]
 [183.00996]
 [181.5696 ]
 [195.50198]
 [141.01465]]
80 Cost:  2.382639 \Prediction:
 [[154.07323]
 [183.01363]
 [181.56792]
 [195.50107]
 [141.01921]]
90 Cost:  2.3726306 \Prediction:
 [[154.06784]
 [183.01727]
 [181.56622]
 [195.50015]
 [141.02374]]
100 C

980 Cost:  1.664718 \Prediction:
 [[153.64198]
 [183.30652]
 [181.43222]
 [195.43028]
 [141.38051]]
990 Cost:  1.6585127 \Prediction:
 [[153.63774]
 [183.30937]
 [181.43086]
 [195.42961]
 [141.38402]]
1000 Cost:  1.6523368 \Prediction:
 [[153.63351]
 [183.31224]
 [181.42953]
 [195.42894]
 [141.38754]]
1010 Cost:  1.6462104 \Prediction:
 [[153.6293 ]
 [183.3151 ]
 [181.42822]
 [195.42828]
 [141.39104]]
1020 Cost:  1.6400745 \Prediction:
 [[153.62508]
 [183.31796]
 [181.4269 ]
 [195.42761]
 [141.39453]]
1030 Cost:  1.6339849 \Prediction:
 [[153.62088]
 [183.32082]
 [181.42557]
 [195.42696]
 [141.39801]]
1040 Cost:  1.6279417 \Prediction:
 [[153.6167 ]
 [183.32364]
 [181.42424]
 [195.4263 ]
 [141.40149]]
1050 Cost:  1.6219113 \Prediction:
 [[153.61253]
 [183.32649]
 [181.42291]
 [195.42564]
 [141.40494]]
1060 Cost:  1.6159289 \Prediction:
 [[153.60837]
 [183.3293 ]
 [181.4216 ]
 [195.425  ]
 [141.4084 ]]
1070 Cost:  1.609981 \Prediction:
 [[153.60422]
 [183.33212]
 [181.4203 ]
 [195.42435

2000 Cost:  1.172566 \Prediction:
 [[153.26201]
 [183.56392]
 [181.31186]
 [195.37352]
 [141.69278]]
